language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - sudo apt-get purge riak
    - sudo curl https://packagecloud.io/install/repositories/basho/riak/script.deb | sudo bash
    - sudo apt-get install riak=2.0.0-1
    - sudo sed -i -e "s/search = off/search = on/g" /etc/riak/riak.conf
    - sudo sed -i -e "s/storage_backend = .*/storage_backend = memory/g" /etc/riak/riak.conf
    - sudo service riak start
    - composer self-update
    - composer --prefer-source install

before_script:
    - ./tests/travis/setup-riak.sh

script:
    - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
    - ./vendor/bin/phpcs -p --extensions=php  --standard=ruleset.xml src

after_script:
    - php ./vendor/bin/coveralls -v
    - php ./vendor/bin/apigen generate -s src -d build/api --title "PHP Riak Client" --template-theme bootstrap
